import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { EnvironmentVariables } from '../../config/env.validation.js';
import { type StoredFile, StorageService } from './storage.service.js';

// Keys are generated by the application, but the read path receives them from
// a URL. Only this exact shape is ever touched on disk: slash-separated
// segments of letters, digits, "-" and "_", ending in ".webp". That rules out
// "..", absolute paths, backslashes and any other file type.
const SAFE_KEY = /^[A-Za-z0-9_-]+(\/[A-Za-z0-9_-]+)*\.webp$/;

export function isSafeStorageKey(key: string): boolean {
  return key.length <= 255 && SAFE_KEY.test(key);
}

@Injectable()
export class LocalStorageService extends StorageService {
  private readonly root: string;

  constructor(config: ConfigService<EnvironmentVariables, true>) {
    super();
    this.root = resolve(config.get('UPLOAD_DIR', { infer: true }));
  }

  async put(key: string, data: Buffer): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, data);
  }

  async get(key: string): Promise<StoredFile | null> {
    if (!isSafeStorageKey(key)) {
      return null;
    }
    try {
      return {
        data: await readFile(join(this.root, key)),
        contentType: 'image/webp',
      };
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        return null;
      }
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  private pathFor(key: string): string {
    if (!isSafeStorageKey(key)) {
      throw new Error(`Unsafe storage key: ${key}`);
    }
    return join(this.root, key);
  }
}
