import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCategoryAdminFields1759881600000 implements MigrationInterface {
  name = 'AddCategoryAdminFields1759881600000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "categories"
        ADD COLUMN "name_en" varchar(80),
        ADD COLUMN "is_active" boolean NOT NULL DEFAULT true
    `);
    await queryRunner.query(`
      UPDATE "categories" SET "name_en" = CASE "slug"
        WHEN 'do-cu' THEN 'Second-hand'
        WHEN 'thuc-pham-tuoi' THEN 'Fresh food'
        WHEN 'do-an' THEN 'Food'
        WHEN 'dien-tu' THEN 'Electronics'
        WHEN 'gia-dung' THEN 'Household'
        WHEN 'khac' THEN 'Other'
        ELSE "name"
      END
    `);
    await queryRunner.query(
      `ALTER TABLE "categories" ALTER COLUMN "name_en" SET NOT NULL`,
    );
    // The seeded rows used hand-written ids 1 to 6; new rows continue at 7.
    await queryRunner.query(`
      ALTER TABLE "categories"
        ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 7)
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "categories" ALTER COLUMN "id" DROP IDENTITY`,
    );
    await queryRunner.query(`
      ALTER TABLE "categories"
        DROP COLUMN "is_active",
        DROP COLUMN "name_en"
    `);
  }
}
