import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  type Relation,
  UpdateDateColumn,
} from 'typeorm';
import { Category } from '../categories/category.entity.js';
import { User } from '../users/user.entity.js';
import { ListingImage } from './listing-image.entity.js';
import { ListingItem } from './listing-item.entity.js';
import { ListingMode, ListingStatus } from './listings.constants.js';

// The search_vector column is generated by the database from search_text and
// is deliberately not mapped here.
@Entity('listings')
export class Listing {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ name: 'seller_id', type: 'uuid' })
  sellerId!: string;

  @ManyToOne(() => User)
  @JoinColumn({ name: 'seller_id' })
  seller!: Relation<User>;

  @Column({ name: 'category_id', type: 'smallint' })
  categoryId!: number;

  @ManyToOne(() => Category)
  @JoinColumn({ name: 'category_id' })
  category!: Relation<Category>;

  @Column({ type: 'varchar', length: 120 })
  title!: string;

  @Column({ type: 'text', default: '' })
  description!: string;

  @Column({ type: 'enum', enum: ListingMode, enumName: 'listings_mode_enum' })
  mode!: ListingMode;

  @Column({
    type: 'enum',
    enum: ListingStatus,
    enumName: 'listings_status_enum',
    default: ListingStatus.Draft,
  })
  status!: ListingStatus;

  @Column({ name: 'accepts_prepaid_qr', type: 'boolean' })
  acceptsPrepaidQr!: boolean;

  @Column({ name: 'accepts_pay_on_delivery', type: 'boolean' })
  acceptsPayOnDelivery!: boolean;

  @Column({ name: 'order_deadline', type: 'timestamptz', nullable: true })
  orderDeadline!: Date | null;

  /** Calendar date, YYYY-MM-DD. */
  @Column({ name: 'delivery_date', type: 'date', nullable: true })
  deliveryDate!: string | null;

  @Column({ name: 'reopened_from_id', type: 'uuid', nullable: true })
  reopenedFromId!: string | null;

  @Column({ name: 'search_text', type: 'text', default: '' })
  searchText!: string;

  @Column({ name: 'published_at', type: 'timestamptz', nullable: true })
  publishedAt!: Date | null;

  @Column({ name: 'closed_at', type: 'timestamptz', nullable: true })
  closedAt!: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @OneToMany(() => ListingItem, (item) => item.listing)
  items!: Relation<ListingItem[]>;

  @OneToMany(() => ListingImage, (image) => image.listing)
  images!: Relation<ListingImage[]>;
}
